app:
  php:
    version: "8.4"
  environment_variables:
    - name: APP_ENV
      value: "production"
      scope: RUN
    - name: APP_DEBUG
      value: "0"
      scope: RUN
    - name: APP_URL
      value: "https://nightly-ats-trunk-479489b2-6c96-4849-89c1-bcbb0d766bb4.production.shopware.shop"
      scope: RUN
services:
  mysql:
    version: "8.0"
  opensearch:
    enabled: false
