app:
  php:
    version: "8.4"
  environment_variables:
    - name: APP_ENV
      value: "production"
      scope: RUN
    - name: APP_DEBUG
      value: "0"
      scope: RUN
    - name: APP_URL
      value: "https://nightly-ats-66x-ad994520-bf4c-48c7-a1c2-75cc587335e9.production.shopware.shop"
      scope: RUN
services:
  mysql:
    version: "8.0"
  opensearch:
    enabled: false
